package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAdmin generated by hbm2java
 */
public class TbActivity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6334135320451881867L;
	private Integer id;
	private String name;
	private String description;
	private int status;
	private int isThresholdSet;
	private String iconPicture;
	private Date createTime;
	private Date modifyTime;
	private String extProps;

	public TbActivity() {
	}

	public TbActivity(String name, String description, int status,
			int isThresholdSet, String iconPicture, Date createTime) {
		super();
		this.name = name;
		this.description = description;
		this.status = status;
		this.isThresholdSet = isThresholdSet;
		this.iconPicture = iconPicture;
		this.createTime = createTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getIsThresholdSet() {
		return isThresholdSet;
	}

	public void setIsThresholdSet(int isThresholdSet) {
		this.isThresholdSet = isThresholdSet;
	}

	public String getIconPicture() {
		return iconPicture;
	}

	public void setIconPicture(String iconPicture) {
		this.iconPicture = iconPicture;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getExtProps() {
		return extProps;
	}

	public void setExtProps(String extProps) {
		this.extProps = extProps;
	}

	@Override
	public String toString() {
		return "TbActivity [id=" + id + ", name=" + name + ", description="
				+ description + ", status=" + status + ", isThresholdSet="
				+ isThresholdSet + ", iconPicture=" + iconPicture
				+ ", createTime=" + createTime + "]";
	}
	
}
