package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAdmin generated by hbm2java
 */
public class TbAdmin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6334135320451881867L;
	private Integer adminId;
	private String adminName;
	private String adminPasswd;
	private int adminLevel;
	private String forgetPasswd;
	private String email;
	private String phoneNum;
	private Date registerTime;
	private Date modifyTime;
	private String extProps;
	private Integer status;

	public TbAdmin() {
	}

	public TbAdmin(String adminName, String adminPasswd, int adminLevel,
			Date registerTime) {
		this.adminName = adminName;
		this.adminPasswd = adminPasswd;
		this.adminLevel = adminLevel;
		this.registerTime = registerTime;
	}

	public TbAdmin(String adminName, String adminPasswd, int adminLevel,
			String adminForgetPasswd, Date registerTime) {
		this.adminName = adminName;
		this.adminPasswd = adminPasswd;
		this.adminLevel = adminLevel;
		this.forgetPasswd = adminForgetPasswd;
		this.registerTime = registerTime;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getAdminPasswd() {
		return this.adminPasswd;
	}

	public void setAdminPasswd(String adminPasswd) {
		this.adminPasswd = adminPasswd;
	}

	public int getAdminLevel() {
		return this.adminLevel;
	}

	public void setAdminLevel(int adminLevel) {
		this.adminLevel = adminLevel;
	}

	public String getForgetPasswd() {
		return forgetPasswd;
	}

	public void setForgetPasswd(String forgetPasswd) {
		this.forgetPasswd = forgetPasswd;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public Date getRegisterTime() {
		return registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getExtProps() {
		return extProps;
	}

	public void setExtProps(String extProps) {
		this.extProps = extProps;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "TbAdmin{" +
				"adminId=" + adminId +
				", adminName='" + adminName + '\'' +
				", adminPasswd='" + adminPasswd + '\'' +
				", adminLevel=" + adminLevel +
				", forgetPasswd='" + forgetPasswd + '\'' +
				", email='" + email + '\'' +
				", phoneNum='" + phoneNum + '\'' +
				", registerTime=" + registerTime +
				", modifyTime=" + modifyTime +
				", extProps='" + extProps + '\'' +
				", status=" + status +
				'}';
	}
}
