package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * TbMchUser generated by hbm2java
 */
public class TbMch implements Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4759292190081752784L;
	private Integer mchId;
	private String mchName;
	private String mchPasswd;
	private String phoneNum;
	private String email;
	private String fkOpenId;
	private String shopDetail;
	private int totalVisitor;
	private int totalSaleCount;
	private int totalFans;
	private int totalMoney;
	private String shopName;
	private String shopAddress;
	private String shopLnglnt;
	private String contentPicture;
	private int mchLelvel;
	private int serviceType;
	private int averageTime;
	private int points;
	private Date registerTime;
	private String serviceStatus;
	private String mchActivity;
	private int mchStatus;
	private String extProps;
	private Date modifyTime;
	
	public TbMch() {
	}

	public TbMch(String mchName, String mchPasswd, int mchTotalIncome,
			int mchLelvel, int mchPoints, int mchStatus) {
		this.mchName = mchName;
		this.mchPasswd = mchPasswd;
		this.mchLelvel = mchLelvel;
		this.mchStatus = mchStatus;
	}

	public TbMch(String mchName, String mchPasswd, int mchTotalIncome,
			int mchLelvel, int mchPoints, Date registerTime, int mchStatus) {
		this.mchName = mchName;
		this.mchPasswd = mchPasswd;
		this.mchLelvel = mchLelvel;
		this.registerTime = registerTime;
		this.mchStatus = mchStatus;
	}


	public TbMch clone() {
		TbMch o = null;
		try {
			o = (TbMch) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return o;
	}

	public Integer getMchId() {
		return mchId;
	}

	public void setMchId(Integer mchId) {
		this.mchId = mchId;
	}

	public String getMchName() {
		return mchName;
	}

	public void setMchName(String mchName) {
		this.mchName = mchName;
	}

	public String getMchPasswd() {
		return mchPasswd;
	}

	public void setMchPasswd(String mchPasswd) {
		this.mchPasswd = mchPasswd;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getShopDetail() {
		return shopDetail;
	}

	public String getContentPicture() {
		return contentPicture;
	}

	public void setContentPicture(String contentPicture) {
		this.contentPicture = contentPicture;
	}

	public void setShopDetail(String shopDetail) {
		this.shopDetail = shopDetail;
	}

	public int getTotalVisitor() {
		return totalVisitor;
	}

	public void setTotalVisitor(int totalVisitor) {
		this.totalVisitor = totalVisitor;
	}

	public int getTotalSaleCount() {
		return totalSaleCount;
	}

	public void setTotalSaleCount(int totalSaleCount) {
		this.totalSaleCount = totalSaleCount;
	}

	public int getTotalFans() {
		return totalFans;
	}

	public void setTotalFans(int totalFans) {
		this.totalFans = totalFans;
	}

	public int getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(int totalMoney) {
		this.totalMoney = totalMoney;
	}

	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopAddress() {
		return shopAddress;
	}

	public void setShopAddress(String shopAddress) {
		this.shopAddress = shopAddress;
	}

	public String getShopLnglnt() {
		return shopLnglnt;
	}

	public void setShopLnglnt(String shopLnglnt) {
		this.shopLnglnt = shopLnglnt;
	}

	public int getMchLelvel() {
		return mchLelvel;
	}

	public void setMchLelvel(int mchLelvel) {
		this.mchLelvel = mchLelvel;
	}

	public int getServiceType() {
		return serviceType;
	}

	public void setServiceType(int serviceType) {
		this.serviceType = serviceType;
	}

	public int getPoints() {
		return points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	public Date getRegisterTime() {
		return registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public String getServiceStatus() {
		return serviceStatus;
	}

	public void setServiceStatus(String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public String getMchActivity() {
		return mchActivity;
	}

	public void setMchActivity(String mchActivity) {
		this.mchActivity = mchActivity;
	}

	public int getMchStatus() {
		return mchStatus;
	}

	public void setMchStatus(int mchStatus) {
		this.mchStatus = mchStatus;
	}

	public String getExtProps() {
		return extProps;
	}

	public void setExtProps(String extProps) {
		this.extProps = extProps;
	}

	public Date getModifyTime() {
		return modifyTime;
	}
	
	public String getFkOpenId() {
		return fkOpenId;
	}

	public void setFkOpenId(String fkOpenId) {
		this.fkOpenId = fkOpenId;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	
	public int getAverageTime() {
		return averageTime;
	}

	public void setAverageTime(int averageTime) {
		this.averageTime = averageTime;
	}

	@Override
	public String toString() {
		return "TbMch{" +
				"mchId=" + mchId +
				", mchName='" + mchName + '\'' +
				", mchPasswd='" + mchPasswd + '\'' +
				", phoneNum='" + phoneNum + '\'' +
				", email='" + email + '\'' +
				", shopDetail='" + shopDetail + '\'' +
				", totalVisitor=" + totalVisitor +
				", totalSaleCount=" + totalSaleCount +
				", totalFans=" + totalFans +
				", totalMoney=" + totalMoney +
				", shopName='" + shopName + '\'' +
				", shopAddress='" + shopAddress + '\'' +
				", shopLnglnt='" + shopLnglnt + '\'' +
				", mchLelvel=" + mchLelvel +
				", serviceType=" + serviceType +
				", points=" + points +
				", registerTime=" + registerTime +
				", serviceStatus='" + serviceStatus + '\'' +
				", mchActivity='" + mchActivity + '\'' +
				", mchStatus=" + mchStatus +
				", extProps='" + extProps + '\'' +
				", modifyTime=" + modifyTime +
				'}';
	}
}
