package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbProduct generated by hbm2java
 */
public class TbProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6414088976126783504L;
	private Integer productId;
	private String productName;
	private int productPrice;
	private int discountPrice;
	private int fkMchId;
	private int saleTotalTimes;
	private int saleTotalMoney;
	private int likeCounts;
	private int dislikeCounts;
	private int productStatus;
	private String productHeadPicture;
	private String productType;
	private String productContentPicture;
	private String productDescription;
	private String extProps;
	private int discountPercent;
	private Date createTime;
	private Date modifyTime;

	public TbProduct() {
	}

	public TbProduct(String productName, int productPrice, int fkMchId,
			int saleTotalTimes, int saleTotalMoney, int likeCounts,
			int discountPercent, Date createTime) {
		this.productName = productName;
		this.productPrice = productPrice;
		this.fkMchId = fkMchId;
		this.saleTotalTimes = saleTotalTimes;
		this.saleTotalMoney = saleTotalMoney;
		this.likeCounts = likeCounts;
		this.discountPercent = discountPercent;
		this.createTime = createTime;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public int getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(int productPrice) {
		this.productPrice = productPrice;
	}

	public int getFkMchId() {
		return this.fkMchId;
	}

	public void setFkMchId(int fkMchId) {
		this.fkMchId = fkMchId;
	}

	public int getSaleTotalTimes() {
		return this.saleTotalTimes;
	}

	public void setSaleTotalTimes(int saleTotalTimes) {
		this.saleTotalTimes = saleTotalTimes;
	}

	public int getSaleTotalMoney() {
		return this.saleTotalMoney;
	}

	public void setSaleTotalMoney(int saleTotalMoney) {
		this.saleTotalMoney = saleTotalMoney;
	}

	public int getLikeCounts() {
		return this.likeCounts;
	}

	public void setLikeCounts(int likeCounts) {
		this.likeCounts = likeCounts;
	}
	
	public int getDislikeCounts() {
		return dislikeCounts;
	}

	public void setDislikeCounts(int dislikeCounts) {
		this.dislikeCounts = dislikeCounts;
	}

	public int getProductStatus() {
		return productStatus;
	}

	public void setProductStatus(int productStatus) {
		this.productStatus = productStatus;
	}

	public String getProductHeadPicture() {
		return productHeadPicture;
	}

	public void setProductHeadPicture(String productHeadPicture) {
		this.productHeadPicture = productHeadPicture;
	}

	public String getProductType() {
		return productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getProductContentPicture() {
		return productContentPicture;
	}

	public void setProductContentPicture(String productContentPicture) {
		this.productContentPicture = productContentPicture;
	}

	public String getProductDescription() {
		return productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public int getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(int discountPercent) {
		this.discountPercent = discountPercent;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public int getDiscountPrice() {
		return discountPrice;
	}

	public void setDiscountPrice(int discountPrice) {
		this.discountPrice = discountPrice;
	}

	public String getExtProps() {
		return extProps;
	}

	public void setExtProps(String extProps) {
		this.extProps = extProps;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Override
	public String toString() {
		return "TbProduct [productId=" + productId + ", productName="
				+ productName + ", productPrice=" + productPrice
				+ ", discountPrice=" + discountPrice + ", fkMchId=" + fkMchId
				+ ", saleTotalTimes=" + saleTotalTimes + ", saleTotalMoney="
				+ saleTotalMoney + ", likeCounts=" + likeCounts
				+ ", dislikeCounts=" + dislikeCounts + ", productStatus="
				+ productStatus + ", productHeadPicture=" + productHeadPicture
				+ ", productType=" + productType + ", productContentPicture="
				+ productContentPicture + ", productDescription="
				+ productDescription + ", discountPercent=" + discountPercent
				+ ", createTime=" + createTime + "]";
	}

}
