package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbProduct generated by hbm2java
 */
public class TbQueueRecord implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -6414088976126783504L;
	private Integer recordId;
	private int fkMchstaffId;
	private String fkOpenId;
	private int fkMchId;
	private int fkTransactionId;
	private String orderId;
	private int isScan;
	private int status ;
	private String extProps;
	private Date startTime;
	private Date endTime;

	public TbQueueRecord() {
	}

	public Integer getRecordId() {
		return recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public int getFkMchstaffId() {
		return fkMchstaffId;
	}

	public void setFkMchstaffId(int fkMchstaffId) {
		this.fkMchstaffId = fkMchstaffId;
	}

	public String getFkOpenId() {
		return fkOpenId;
	}

	public void setFkOpenId(String fkOpenId) {
		this.fkOpenId = fkOpenId;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public int getFkMchId() {
		return fkMchId;
	}

	public void setFkMchId(int fkMchId) {
		this.fkMchId = fkMchId;
	}
	
	public int getFkTransactionId() {
		return fkTransactionId;
	}

	public void setFkTransactionId(int fkTransactionId) {
		this.fkTransactionId = fkTransactionId;
	}

	public int getIsScan() {
		return isScan;
	}

	public void setIsScan(int isScan) {
		this.isScan = isScan;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getExtProps() {
		return extProps;
	}

	public void setExtProps(String extProps) {
		this.extProps = extProps;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Override
	public String toString() {
		return "TbQueueRecord{" +
				"recordId=" + recordId +
				", fkMchstaffId=" + fkMchstaffId +
				", fkOpenId='" + fkOpenId + '\'' +
				", fkMchId=" + fkMchId +
				", fkTransactionId=" + fkTransactionId +
				", isScan=" + isScan +
				", status=" + status +
				", extProps='" + extProps + '\'' +
				", startTime=" + startTime +
				", endTime=" + endTime +
				'}';
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((fkOpenId == null) ? 0 : fkOpenId.hashCode());
		result = prime * result
				+ ((recordId == null) ? 0 : recordId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TbQueueRecord other = (TbQueueRecord) obj;
		if (fkOpenId == null) {
			if (other.fkOpenId != null)
				return false;
		} else if (!fkOpenId.equals(other.fkOpenId))
			return false;
		if (recordId == null) {
			if (other.recordId != null)
				return false;
		} else if (!recordId.equals(other.recordId))
			return false;
		return true;
	}
	
	
	
}
