package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbRedeemCode generated by hbm2java
 */
public class TbRedeemCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4569658457338524424L;
	private Integer codeId;
	private String randomCode;
	private Integer fkProductId;
	private boolean isUsed;
	private Date usedTime;
	private int createType;
	private int productNum;
	private Integer fkMchId;
	private Integer payMoney;
	private String fkOpenId; //微信账户的 用户 open Id
	private Date validDate;
	private String codeInfo;
	private int isSendok;
	private Date codeCreateTime;

	public TbRedeemCode() {
	}

	public TbRedeemCode(String randomCode, boolean isUsed, Date usedTime,
			int createType, int productNum, Date codeCreateTime) {
		this.randomCode = randomCode;
		this.isUsed = isUsed;
		this.usedTime = usedTime;
		this.createType = createType;
		this.productNum = productNum;
		this.codeCreateTime = codeCreateTime;
	}

	public TbRedeemCode(String randomCode, Integer fkProductId, boolean isUsed,
			Date usedTime, int createType, int productNum, Integer fkMchId,
			Integer payMoney, Date validDate, String codeInfo,
			Date codeCreateTime) {
		this.randomCode = randomCode;
		this.fkProductId = fkProductId;
		this.isUsed = isUsed;
		this.usedTime = usedTime;
		this.createType = createType;
		this.productNum = productNum;
		this.fkMchId = fkMchId;
		this.payMoney = payMoney;
		this.validDate = validDate;
		this.codeInfo = codeInfo;
		this.codeCreateTime = codeCreateTime;
	}

	public Integer getCodeId() {
		return this.codeId;
	}

	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}

	public String getRandomCode() {
		return this.randomCode;
	}

	public void setRandomCode(String randomCode) {
		this.randomCode = randomCode;
	}

	public Integer getFkProductId() {
		return this.fkProductId;
	}

	public void setFkProductId(Integer fkProductId) {
		this.fkProductId = fkProductId;
	}

	public boolean isIsUsed() {
		return this.isUsed;
	}

	public void setIsUsed(boolean isUsed) {
		this.isUsed = isUsed;
	}

	public Date getUsedTime() {
		return this.usedTime;
	}

	public void setUsedTime(Date usedTime) {
		this.usedTime = usedTime;
	}

	public int getCreateType() {
		return this.createType;
	}

	public void setCreateType(int createType) {
		this.createType = createType;
	}

	public int getProductNum() {
		return this.productNum;
	}

	public void setProductNum(int productNum) {
		this.productNum = productNum;
	}

	public Integer getFkMchId() {
		return this.fkMchId;
	}

	public void setFkMchId(Integer fkMchId) {
		this.fkMchId = fkMchId;
	}

	public Integer getPayMoney() {
		return this.payMoney;
	}

	public void setPayMoney(Integer payMoney) {
		this.payMoney = payMoney;
	}

	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	public String getCodeInfo() {
		return this.codeInfo;
	}

	public void setCodeInfo(String codeInfo) {
		this.codeInfo = codeInfo;
	}

	public Date getCodeCreateTime() {
		return this.codeCreateTime;
	}

	public void setCodeCreateTime(Date codeCreateTime) {
		this.codeCreateTime = codeCreateTime;
	}

	public boolean isUsed() {
		return isUsed;
	}

	public void setUsed(boolean isUsed) {
		this.isUsed = isUsed;
	}

	public int getIsSendok() {
		return isSendok;
	}

	public void setIsSendok(int isSendok) {
		this.isSendok = isSendok;
	}

	public String getFkOpenId() {
		return fkOpenId;
	}

	public void setFkOpenId(String fkOpenId) {
		this.fkOpenId = fkOpenId;
	}

	@Override
	public String toString() {
		return "TbRedeemCode [codeId=" + codeId + ", randomCode=" + randomCode
				+ ", fkProductId=" + fkProductId + ", isUsed=" + isUsed
				+ ", usedTime=" + usedTime + ", createType=" + createType
				+ ", productNum=" + productNum + ", fkMchId=" + fkMchId
				+ ", payMoney=" + payMoney + ", fkWechatUserId="
				+ fkOpenId + ", validDate=" + validDate + ", codeInfo="
				+ codeInfo + ", isSendok=" + isSendok + ", codeCreateTime="
				+ codeCreateTime + "]";
	}

	
}
