package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbTransactionRecord generated by hbm2java
 */
public class TbTransactionRecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6886370619970430623L;
	private Integer recordId;
	private int fkProductId;
	private int fkMchId;
	private int fkStaffId;
	private String fkOpenId;
	private int recordMoney;
	private Date recordTime;
	private String outTradeNo;
	private String recordType;
	private int recordStatus;
	private int productNum;
	private int isScaned;
	private String extProps;
	

	public TbTransactionRecord() {
	}

	public TbTransactionRecord(int fkProductId, int fkMchId,int recordMoney, Date recordTime, int recordStatus) {
		this.fkProductId = fkProductId;
		this.fkMchId = fkMchId;
		this.recordMoney = recordMoney;
		this.recordTime = recordTime;
		this.recordStatus = recordStatus;
	}

	public TbTransactionRecord(int fkProductId, int fkMchId,
			int recordMoney, Date recordTime, String outTradeNo,
			int recordStatus) {
		this.fkProductId = fkProductId;
		this.fkMchId = fkMchId;
		this.recordMoney = recordMoney;
		this.recordTime = recordTime;
		this.outTradeNo = outTradeNo;
		this.recordStatus = recordStatus;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public int getFkProductId() {
		return this.fkProductId;
	}

	public void setFkProductId(int fkProductId) {
		this.fkProductId = fkProductId;
	}

	public int getFkMchId() {
		return this.fkMchId;
	}

	public void setFkMchId(int fkMchId) {
		this.fkMchId = fkMchId;
	}

	public String getFkOpenId() {
		return fkOpenId;
	}

	public void setFkOpenId(String fkOpenId) {
		this.fkOpenId = fkOpenId;
	}

	public int getRecordMoney() {
		return this.recordMoney;
	}

	public void setRecordMoney(int recordMoney) {
		this.recordMoney = recordMoney;
	}

	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	public int getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(int recordStatus) {
		this.recordStatus = recordStatus;
	}

	public int getProductNum() {
		return productNum;
	}

	public void setProductNum(int productNum) {
		this.productNum = productNum;
	}

	public int getIsScaned() {
		return isScaned;
	}

	public void setIsScaned(int isScaned) {
		this.isScaned = isScaned;
	}

	public String getExtProps() {
		return extProps;
	}

	public void setExtProps(String extProps) {
		this.extProps = extProps;
	}
	
	public int getFkStaffId() {
		return fkStaffId;
	}

	public void setFkStaffId(int fkStaffId) {
		this.fkStaffId = fkStaffId;
	}
	
	public String getRecordType() {
		return recordType;
	}

	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	@Override
	public String toString() {
		return "TbTransactionRecord [recordId=" + recordId + ", fkProductId="
				+ fkProductId + ", fkMchId=" + fkMchId + ", fkStaffId="
				+ fkStaffId + ", fkOpenId=" + fkOpenId + ", recordMoney="
				+ recordMoney + ", recordTime=" + recordTime + ", outTradeNo="
				+ outTradeNo + ", recordType=" + recordType + ", recordStatus="
				+ recordStatus + ", productNum=" + productNum + ", isScaned="
				+ isScaned + ", extProps=" + extProps + "]";
	}


}
