package happylife.model;

// Generated 2016-5-21 15:47:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbWechatMsg generated by hbm2java
 */
public class TbWechatMsg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6795669219822336729L;
	private String id;
	private String content;
	private String signType;
	private String inputCharset;
	private String sign;
	private String tradeMode;
	private String tradeState;
	private String partner;
	private String bankType;
	private String bankBillno;
	private String totalFee;
	private String feeType;
	private String notifyId;
	private String transactionId;
	private String outTradeNo;
	private String attach;
	private String timeEnd;
	private String transportFee;
	private String productFee;
	private String discount;
	private Date time;

	public TbWechatMsg() {
	}

	public TbWechatMsg(String id) {
		this.id = id;
	}

	public TbWechatMsg(String id, String content, String signType,
			String inputCharset, String sign, String tradeMode,
			String tradeState, String partner, String bankType,
			String bankBillno, String totalFee, String feeType,
			String notifyId, String transactionId, String outTradeNo,
			String attach, String timeEnd, String transportFee,
			String productFee, String discount, Date time) {
		this.id = id;
		this.content = content;
		this.signType = signType;
		this.inputCharset = inputCharset;
		this.sign = sign;
		this.tradeMode = tradeMode;
		this.tradeState = tradeState;
		this.partner = partner;
		this.bankType = bankType;
		this.bankBillno = bankBillno;
		this.totalFee = totalFee;
		this.feeType = feeType;
		this.notifyId = notifyId;
		this.transactionId = transactionId;
		this.outTradeNo = outTradeNo;
		this.attach = attach;
		this.timeEnd = timeEnd;
		this.transportFee = transportFee;
		this.productFee = productFee;
		this.discount = discount;
		this.time = time;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSignType() {
		return this.signType;
	}

	public void setSignType(String signType) {
		this.signType = signType;
	}

	public String getInputCharset() {
		return this.inputCharset;
	}

	public void setInputCharset(String inputCharset) {
		this.inputCharset = inputCharset;
	}

	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getTradeMode() {
		return this.tradeMode;
	}

	public void setTradeMode(String tradeMode) {
		this.tradeMode = tradeMode;
	}

	public String getTradeState() {
		return this.tradeState;
	}

	public void setTradeState(String tradeState) {
		this.tradeState = tradeState;
	}

	public String getPartner() {
		return this.partner;
	}

	public void setPartner(String partner) {
		this.partner = partner;
	}

	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	public String getBankBillno() {
		return this.bankBillno;
	}

	public void setBankBillno(String bankBillno) {
		this.bankBillno = bankBillno;
	}

	public String getTotalFee() {
		return this.totalFee;
	}

	public void setTotalFee(String totalFee) {
		this.totalFee = totalFee;
	}

	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	public String getNotifyId() {
		return this.notifyId;
	}

	public void setNotifyId(String notifyId) {
		this.notifyId = notifyId;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	public String getAttach() {
		return this.attach;
	}

	public void setAttach(String attach) {
		this.attach = attach;
	}

	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getTransportFee() {
		return this.transportFee;
	}

	public void setTransportFee(String transportFee) {
		this.transportFee = transportFee;
	}

	public String getProductFee() {
		return this.productFee;
	}

	public void setProductFee(String productFee) {
		this.productFee = productFee;
	}

	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
